# Generated by Django 4.2.1 on 2023-05-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtolonRostVes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vozrast', models.IntegerField(verbose_name='Возраст')),
                ('rost_malch', models.IntegerField(verbose_name='Рост мальчика')),
                ('otklon_rost_malch', models.IntegerField(verbose_name='Отклонение в росте мальчика')),
                ('ves_malch', models.FloatField(verbose_name='Вес мальчика')),
                ('otklon_ves_malch', models.FloatField(verbose_name='Отклонение в весе мальчика')),
                ('rost_devoch', models.IntegerField(verbose_name='Рост девочки')),
                ('otklon_rost_devoch', models.IntegerField(verbose_name='Отклонение в росте девочки')),
                ('ves_devoch', models.FloatField(verbose_name='Вес девочки')),
                ('otklon_ves_devoch', models.FloatField(verbose_name='Отклоненипе в весе девочки')),
            ],
            options={
                'verbose_name': 'Эталонный рост вес',
                'verbose_name_plural': 'Эталонный рост вес',
            },
        ),
        migrations.CreateModel(
            name='Harakteristiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_harakteristiki', models.CharField(max_length=255, verbose_name='Название характеристики')),
                ('opisanie_harakteristiki', models.CharField(max_length=255, verbose_name='Описание характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='KategorPolz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(max_length=255, verbose_name='Категория пользователя')),
                ('opisanie', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория пользователя',
                'verbose_name_plural': 'Категории пользователей',
            },
        ),
        migrations.CreateModel(
            name='Polzovateli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('parol', models.CharField(max_length=255, verbose_name='Пароль')),
                ('ID_kategorii', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='ProgrammUmnKom.kategorpolz', verbose_name='Категория пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Rezultaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imya_reb', models.CharField(max_length=255, verbose_name='Имя ребенка')),
                ('pol_reb', models.CharField(max_length=255, verbose_name='Пол ребенка')),
                ('vozr_reb', models.IntegerField(verbose_name='Возраст ребенка')),
                ('date_prohoj_test', models.DateTimeField(verbose_name='Дата прохождения тестирования')),
                ('rost', models.IntegerField(verbose_name='verbose_name=Рост')),
                ('ves', models.FloatField(verbose_name='Вес')),
                ('ID_polzovatelya', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ProgrammUmnKom.polzovateli', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='VidSporta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie_vida', models.CharField(max_length=255, verbose_name='Название вида спорта')),
                ('opisanie', models.CharField(max_length=255, verbose_name='Описание вида спорта')),
                ('etalon_sila', models.IntegerField(verbose_name='Эталонная сила')),
                ('etalon_vinos', models.IntegerField(verbose_name='Эталонная выносливость')),
                ('etalon_skorost', models.IntegerField(verbose_name='Эталонная скорость')),
                ('etalon_gibkost', models.IntegerField(verbose_name='Эталонная гибкость')),
                ('etalon_koord', models.IntegerField(verbose_name='Эталонная координация')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='Uprajneniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uprajnen', models.CharField(max_length=255, verbose_name='Упражнение')),
                ('pravila_vipolnen', models.CharField(max_length=255, verbose_name='Правила выполнения')),
                ('vozrast', models.IntegerField(verbose_name='Возраст')),
                ('pol', models.CharField(max_length=255, verbose_name='Пол')),
                ('normativ_na_6', models.FloatField(verbose_name='Норматив на 6')),
                ('normativ_na_5', models.FloatField(verbose_name='Норматив на 5')),
                ('normativ_na_4', models.FloatField(verbose_name='Норматив на 4')),
                ('normativ_na_3', models.FloatField(verbose_name='Норматив на 3')),
                ('id_harakter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ProgrammUmnKom.harakteristiki', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='RezulUpr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resul_upr', models.IntegerField(verbose_name='Результат упражнения')),
                ('ID_resul', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ProgrammUmnKom.rezultaty', verbose_name='Результат')),
                ('ID_upr', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ProgrammUmnKom.uprajneniya', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Результат упражнения',
                'verbose_name_plural': 'Результаты упражнений',
            },
        ),
        migrations.AddField(
            model_name='rezultaty',
            name='ID_vida_sporta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ProgrammUmnKom.vidsporta', verbose_name='Вид спорта'),
        ),
        migrations.CreateModel(
            name='HarakterisSporta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_harakter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ProgrammUmnKom.harakteristiki', verbose_name='Характеристика')),
                ('ID_vida_sporta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ProgrammUmnKom.vidsporta', verbose_name='Название вида спорта')),
            ],
            options={
                'verbose_name': 'Характеристика спорта',
                'verbose_name_plural': 'Характеристики спорта',
            },
        ),
    ]
